In [1]:
import pyodbc
import pandas as pd 
import matplotlib.pyplot as plt 
import plotly.express as px
import seaborn as sns
import numpy as np 
from sqlalchemy import create_engine

In [2]:
server = 'localhost, 1433'
database = 'TIMAU'
username= 'SA'
password = 'wUtang!#'

conn_str = f"mssql+pyodbc://{username}:{password}@{server}/{database}?driver=ODBC+Driver+18+for+SQL+Server&TrustServerCertificate=yes"

engine = create_engine(conn_str)
conn = engine.connect()

In [3]:
df = pd.read_sql_query("SELECT TOP 100* FROM OINV WHERE \"CANCELED\" = 'N'", conn)
df.head()

,DocEntry,DocNum,DocType,CANCELED,Handwrtten,Printed,DocStatus,InvntSttus,Transfered,ObjType,...,U_ModeTrns,U_Weight,U_ObjectId,U_ObjectType,U_ITEMGROUP,U_FiscalSaleType,U_FiscalSeal,U_CUIN,U_FiscalFooter,U_Type
0,1,1,S,N,N,Y,C,C,N,13,...,None,None,None,None,None,None,None,None,None,None
1,2,2,S,N,N,N,C,C,N,13,...,None,None,None,None,None,None,None,None,None,None
2,3,3,S,N,N,Y,C,C,N,13,...,None,None,None,None,None,None,None,None,None,None
3,4,4,S,N,N,N,C,C,N,13,...,None,None,None,None,None,None,None,None,None,None
4,5,5,S,N,N,N,C,C,N,13,...,None,None,None,None,None,None,None,None,None,None

In [4]:
df.tail(20)

,DocEntry,DocNum,DocType,CANCELED,Handwrtten,Printed,DocStatus,InvntSttus,Transfered,ObjType,...,U_ModeTrns,U_Weight,U_ObjectId,U_ObjectType,U_ITEMGROUP,U_FiscalSaleType,U_FiscalSeal,U_CUIN,U_FiscalFooter,U_Type
80,81,81,S,N,N,N,C,C,N,13,...,None,None,None,None,None,None,None,None,None,None
81,82,82,S,N,N,N,C,C,N,13,...,None,None,None,None,None,None,None,None,None,None
82,83,83,S,N,N,N,C,C,N,13,...,None,None,None,None,None,None,None,None,None,None
83,84,84,S,N,N,Y,C,C,N,13,...,None,None,None,None,None,None,None,None,None,None
84,85,85,S,N,N,Y,O,C,N,13,...,None,None,None,None,None,None,None,None,None,None
85,86,86,S,N,N,Y,O,C,N,13,...,None,None,None,None,None,None,None,None,None,None
86,87,87,S,N,N,Y,O,C,N,13,...,None,None,None,None,None,None,None,None,None,None
87,88,88,S,N,N,N,C,C,N,13,...,None,None,None,None,None,None,None,None,None,None
88,89,89,S,N,N,N,C,C,N,13,...,None,None,None,None,None,None,None,None,None,None
89,90,90,S,N,N,N,C,C,N,13,...,None,None,None,None,None,None,None,None,None,None
90,91,91,S,N,N,N,C,C,N,13,...,None,None,None,None,None,None,None,None,None,None
91,92,92,S,N,N,N,C,C,N,13,...,None,None,None,None,None,None,None,None,None,None
92,93,93,S,N,N,N,C,C,N,13,...,None,None,None,None,None,None,None,None,None,None
93,94,94,S,N,N,N,C,C,N,13,...,None,None,None,None,None,None,None,None,None,None
94,95,95,S,N,N,N,C,C,N,13,...,None,None,None,None,None,None,None,None,None,None
95,96,96,S,N,N,N,C,C,N,13,...,None,None,None,None,None,None,None,None,None,None
96,97,97,S,N,N,N,C,C,N,13,...,None,None,None,None,None,None,None,None,None,None
97,98,98,S,N,N,N,C,C,N,13,...,None,None,None,None,None,None,None,None,None,None
98,99,99,S,N,N,N,C,C,N,13,...,None,None,None,None,None,None,None,None,None,None
99,100,100,S,N,N,N,C,C,N,13,...,None,None,None,None,None,None,None,None,None,None